### ISSUE TITLE
1-0 queries is still a thing it seems

### ISSUE THREAD

**Issue by xefibo** [christophrus/CensusPlusClassic#11]
The fix from https://github.com/christophrus/CensusPlusClassic/commit/0b7c3e0c4e21df80a4964c29024364d1775b2e0b did not help I am afraid.

Pic: https://gyazo.com/e419353c5e51900cbecf7c68c4ed62e5

Edit: 
To clarify, this will go on forever if not manually stopped. 
Version 0.5.0.

**Comment by Ommand-** [comment]
I'm getting the same issue.  CensusPlusClassic v0.5.0

**Comment by Talimar** [comment]
Did you try this fix? 
https://github.com/christophrus/CensusPlusClassic/pull/13

**Comment by xefibo** [comment]
I have now edited lines 1592 and 1597 according to https://github.com/christophrus/CensusPlusClassic/pull/13 and restarted the client. I can confirm that the 1-0 query issue is now gone :)

This ticket may be closed when https://github.com/christophrus/CensusPlusClassic/pull/13 is merged and uploaded to Curse.

**Comment by xefibo** [comment]
Might have been too quick there. It did indeed finish once without me stopping it, but the second time around my census failed to stop by itself and the queries in queue kept increasing.  https://gyazo.com/d47a5c4275da02ec908a276e509c3c14

**Comment by vahlback** [comment]
I found a fix. Extremely simple. Change
`if (minLevel ~= maxLevel and minLevel ~= 0) then`
to
`if (minLevel < maxLevel) then`

on line 565

**Comment by Ommand-** [comment]
In addition to the changes in PR # 13 @vahlback vahlback??

**Comment by vahlback** [comment]
@Ommand-
No, I didn't even know about that when I was trying to fix the code. My addon works with just the change I proposed.

**Comment by Ommand-** [comment]
@vahlback 

Thanks, I'll give it a try.

**Comment by Ommand-** [comment]
@vahlback 

I believe your change fixed it, hasn't gotten stuck at 1-0 all evening.

**Comment by xefibo** [comment]
@vahlback @Ommand-  @Corazu
I am now running with both lines Corazus lines 1592 and 1597 and Vahlbacks line 565 edited. While the first fix from PR https://github.com/christophrus/CensusPlusClassic/pull/13 did help sometimes I have now run several censuses without issue after editing 565 as well.

I am not familiar enough with GitHub to make a PR of my own.

**Comment by vahlback** [comment]
@xefibo i believe the 1592/1597 edits are unnecessary. That code is in CencusPlus_CreateWhoText() which creates the /who text string to send as query. Line 565 is in CP_ProcessWhoEvent() which contains the algorithm that splits the level brackets into smaller brackets if there are more than 50 results from a given query, and is where i believe the actual bug occurs.

I'll try making a pull request and commiting the fix to it.

edit: done: https://github.com/christophrus/CensusPlusClassic/pull/15

**Comment by xefibo** [comment]
@vahlback Yea, that was kind of my guess. But on the other hand I was not sure. Anyway, thank you and well done.

**Comment by Corazu** [comment]
#13 and #15 have been merged.
