### ISSUE TITLE
AddOn breaking /who

### ISSUE THREAD

**Issue by jom-jom** [christophrus/CensusPlusClassic#17]
Hi, the AddOn seems to break /who completely. It doesn't matter what you're querying for - there is no result. It retries several times and returns a Timeout. Stopping the census (which doesn't work because of the /who issue) process doesn't resolve the issue.

Deactivating the addon restores the complete /who-functionality. Appeared today (2019-09-19) on game version 1.13.2.31882

A hotfix was installed by the Blizzard App right before launching the game and experiencing the issue for the first time.

Newest Addon version is installed via the twitch client.

**Comment by jom-jom** [comment]
Installed Adons:

  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.1.12
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.52
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.13
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.07
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dismounter, v1.1.0
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  EZJunk, v1.0.1
  FieldGuide, vv1.5-release
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemTooltipProfessionIcons, v1.1.1
  LeatrixMaps, v1.13.31
  RealMobHealth, v2.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.6
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TinyTooltip, v8.2.1
  Titan, v5.17.1.80100
  TitanBag, v5.17.1.80100
  TitanClock, v5.17.1.80100
  TitanGold, v5.17.1.80100
  TitanLocation, v5.17.1.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.1.80100
  TitanReloadUI, v1.0
  TitanRepair, v5.17.1.80100
  TitanShard, v4.3.1.30300
  TitanVolume, v5.17.1.80100
  TitanXP, v5.17.1.80100
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_deDE v1.13.2.11302 <none>

**Comment by vahlback** [comment]
Yes, it seems Blizzard disabled the sendWho() API call in a hotfix yesterday. Addons can no longer use this function. This breaks all Census addons. There's speculation that this was done to limit LFG addons, Census is just collateral damage. Damn shame. I'm not aware of a workaround atm.
