### ISSUE TITLE
Wowclassicpopulation.com

### ISSUE THREAD

**Issue by ryan-dorman** [christophrus/CensusPlusClassic#20]
I can seem to access wowclassicpopulation.com to upload my data.

- It looks like you're still using your self-signed cert
- When visiting the http version of the site I just see the create-react-app default site

![bug_09-29-2019](https://user-images.githubusercontent.com/27789157/65841733-65317a00-e2da-11e9-80d7-3106cceb37e7.png)

**Comment by nseemann** [comment]
The website has been down for months, but it really doesn't matter as the Census addon itself has been broken by Blizzard restricting the SendWho() function, so no new data can be gathered.

**Comment by omggga** [comment]
Its working without www.
https://wowclassicpopulation.com
