### ISSUE TITLE
attempt to call method 'HookScript' (a string value)

### ISSUE THREAD

**Issue by zazomazzo** [christophrus/CensusPlusClassic#25]
I get this error using v0.81 every time reloading UI or logging in.
The addon still seems to work though.
(Both semi automatic options enabled)

1x ...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:529: attempt to call method 'HookScript' (a string value)
...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:529: in function 'InitializeExperimental'
...rfaceCensusPlusClassic\CensusPlusClassic-1.13.2.lua:1685: in function <...rfaceCensusPlusClassic\CensusPlusClassic.lua:1655>

**Comment by christophrus** [comment]
Try to enable the world clicks options only. The interface clicks option breaks with some other addons installed.

**Comment by zazomazzo** [comment]
> Try to enable the world clicks options only. The interface clicks option breaks with some other addons installed.

Yep, that did the trick. Thanks for answering so fast. :)
