### ISSUE TITLE
The "on mouse clicks in the 3D window" does not works for me

### ISSUE THREAD

**Issue by Krabator** [christophrus/CensusPlusClassic#26]
I have installed the addon and select both of the refresh feature, I have selected the verbose mode in order to check the scan refresh

What I expect : Each time I left or right click in the 3D world in order to rotate camera or run, a new scan shall be launched"
What is presently happening : No refresh

I use ElvUI, don't know if it's important

**Comment by christophrus** [comment]
Have you /reload after you checked those options?

**Comment by Krabator** [comment]
yes
/reload and /reloadui
the second feature is working properly : when i call a bind it's lauching a new /who request

**Comment by christophrus** [comment]
Could you deactivate all other addons and reactivate one by one to find out what addon is actually causing this?

**Comment by christophrus** [comment]
Someone in discord had a similar issue with bartender installed. Can you try again with only the first option (clicks in world) checked?
