### ISSUE TITLE
LUA Error when entering BG

### ISSUE THREAD

**Issue by Nixxen** [christophrus/CensusPlusClassic#31]
`Message: ...rface\AddOns\CensusPlusClassic\CensusPlusClassic.lua:2548: attempt to perform arithmetic on field 'g_NumNewCharacters' (a nil value)`

**Comment by mroswald** [comment]
Also, people in battlegrounds will land in the datafile (with empty dataset). Is that expected?

**Comment by christophrus** [comment]
@mroswald No its not wanted and I think we need to add a isInBg check for the manualwho function to prevent it running while in BG. I'll take a look on it, when I find the time.
