### ISSUE TITLE
Level filter ignored in player list

### ISSUE THREAD

**Issue by Road-block** [christophrus/CensusPlusClassic#32]
v0.8.4

[modules/CensusPlayerList.lua#L90](https://github.com/christophrus/CensusPlusClassic/blob/0040e203c0a46e27430edb4820dc3545994cb244/modules/CensusPlayerList.lua#L90)

needs changing to
```lua
levelKey = CPp.LevelSelected;
```

**Comment by christophrus** [comment]
Thanks @Road-block
